# Generates data/ag_ui.json from the reference Python SDK's pydantic models
# (clone github.com/ag-ui-protocol/ag-ui and point AG_UI_SDK at sdks/python).
#
# Run: uv run --with pydantic data/generate-ag-ui-schema.py [/path/to/ag-ui/sdks/python]
#
# Output shape mirrors a2a's data/a2a.json: a single top-level "definitions"
# map keyed by model class name, refs rewritten to #/definitions/<Model>.
# Wire keys are camelCase (by_alias), matching @ag-ui/core exactly.

import inspect
import json
import os
import sys

sdk = sys.argv[1] if len(sys.argv) > 1 else os.environ.get("AG_UI_SDK", "/tmp/ag-ui/sdks/python")
sys.path.insert(0, sdk)

from pydantic import BaseModel  # noqa: E402
from pydantic.json_schema import models_json_schema  # noqa: E402

from ag_ui.core import capabilities, events, types  # noqa: E402

models = []
for mod in (types, events, capabilities):
    for _name, obj in sorted(vars(mod).items()):
        if (
            inspect.isclass(obj)
            and issubclass(obj, BaseModel)
            and obj.__module__ == mod.__name__
            and obj.__name__ != "ConfiguredBaseModel"
        ):
            models.append(obj)

_, top = models_json_schema(
    [(m, "validation") for m in models],
    by_alias=True,
    ref_template="#/definitions/{model}",
)

out = {
    "$comment": f"Generated by data/generate-ag-ui-schema.py from ag-ui sdks/python ({len(models)} models). Do not edit.",
    "definitions": top["$defs"],
}

dest = os.path.join(os.path.dirname(os.path.abspath(__file__)), "ag_ui.json")
with open(dest, "w") as f:
    json.dump(out, f, indent=2, sort_keys=True)
    f.write("\n")

print(f"wrote {dest}: {len(out['definitions'])} definitions")
